name: CI/CD with Auto Rollback

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cicd-project:${{ github.sha }} .

      - name: Run tests
        run: docker run cicd-project:${{ github.sha }} npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd cicd-project || git clone https://github.com/sujandeeep/cicd-project.git
            cd cicd-project

            git pull origin main

            docker stop app || true
            docker rm app || true

            docker build -t cicd-project:test .
            docker run -d -p 80:3000 --name app cicd-project:test